name: Release & Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history required for semantic-release

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js v20
          registry-url: 'https://registry.npmjs.org/' # Set npm registry

      - name: Install Yarn 4
        run: corepack enable && corepack prepare yarn@4 --activate # Enable and activate Yarn v4

      - name: Install dependencies
        run: yarn install --immutable # Install dependencies with exact versions

      - name: Validate Conventional Commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs # Use local commitlint config

        # Allowed semantic PR types
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |-
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            BREAKING CHANGE

      - name: Publish package on NPM 📦
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub authentication
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # npm authentication
        run: npx semantic-release # Run semantic-release for versioning and publishing
      - run: echo "Published to NPM 🚀- https://www.npmjs.com/package/${{ github.event.repository.name }}"

