name: Release & Publish
run-name: ${{ github.actor }} release & publish to npm 🚀

on:
  pull_request:
    types: [closed]
    branches:
      - main
  # Trigger the workflow only when the PR is merged
  # types: [merged]


  # we are using workflow_run to trigger the workflow
  # because we want to run this workflow only when the Commit & PR Lint workflow is completed
  # GitHub prevents workflows from running on events that were caused by other workflows to prevent unlimited recursion
  # so we do not use the release event
  # issue: https://github.com/orgs/community/discussions/25281
  # see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
  # workflow_run:
  #   # the workflow we want to trigger this workflow (see .github/workflows/commitlint.yml)
  #   workflows: [Commit & PR Lint]
  #   # we only want to run this workflow when the Commit & PR Lint workflow is successful
  #   types: [completed]


jobs:
  # Build the project after commit linting is successful
  build:
    runs-on: ubuntu-latest
    # if: |
    #   github.event_name == 'push' &&
    #   github.ref == 'refs/heads/main' &&
    #   github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn 4
        run: corepack enable && corepack prepare yarn@4 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Yarn 4
        run: corepack enable && corepack prepare yarn@4 --activate

      - name: Install dependencies
        run: yarn install --immutable

      # Publish the package to NPM using semantic-release
      - name: Publish package on NPM 📦
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      # Optional: Show the NPM package link after publishing
      - name: Show NPM package link
        run: echo "Published to NPM 🚀- https://www.npmjs.com/package/${{ github.event.repository.name }}"
